#!/bin/bash
#
# Build the docker images in the compose file.

if [ -f ".env" ]; then
  source ".env"
fi

docker compose -f docker-compose.yml -f docker-compose-build.yml build --progress=plain --pull $@
