#!/bin/bash
#
# Build the docker images in the compose file.

if [ -f ".env" ]; then
  source ".env"
fi

if [ ! -f "appsettings.Production.json" ]; then
  echo "{}" > "appsettings.Production.json"
fi

docker compose -f docker-compose.yml -f docker-compose-build.yml build --pull $@
