#!/bin/bash
#
# Start the docker compose application in debug mode.

set -e

if [ -f ".env" ]; then
  source ".env"
fi

if [ ! -f "appsettings.Debug.json" ]; then
  echo "{}" > "appsettings.Debug.json"
fi

mkdir -p data
docker compose -f docker-compose.yml -f docker-compose-debug.yml -f docker-compose-build.yml build

if [ $# -eq 0 ]; then
    docker compose -f docker-compose.yml -f docker-compose-debug.yml up
else
    docker compose -f docker-compose.yml -f docker-compose-debug.yml up $@
fi
