#!/bin/bash
#
# Start the docker compose application in debug mode.

docker-compose -f docker-compose.yml -f docker-compose-debug.yml pull
docker-compose -f docker-compose.yml -f docker-compose-debug.yml up
