name: arcadeia

x-logging:
  &default-logging
  driver: json-file
  options:
    max-size: '1m'
    max-file: '5'

services:
  solr:
    image: solr:8.11.1
    restart: unless-stopped
    logging: *default-logging
    environment:
      - SOLR_HEAP=2g
    command:
      - solr-precreate
      - Library
    networks:
      - internal
    volumes:
      - solr:/var/solr
  app:
    image: ${CONTAINER_REGISTRY:-ghcr.io/travelonium}/arcadeia:${CONTAINER_TAG:-latest}
    entrypoint: ["/usr/bin/dotnet", "/var/lib/app/Arcadeia.dll"]
    working_dir: /var/lib/app
    stop_signal: SIGINT
    logging: *default-logging
    depends_on:
      - solr
    privileged: true
    cap_add:
      - SYS_ADMIN
      - DAC_READ_SEARCH
    networks:
      - internal
    volumes:
      - uploads:/Uploads
  apache:
    image: httpd:2.4.54
    stop_signal: SIGWINCH
    logging: *default-logging
    depends_on:
      - app
    networks:
      - internal
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - type: bind
        source: ./Apache/usr/local/apache2/conf/httpd.conf
        target: /usr/local/apache2/conf/httpd.conf
        consistency: cached
        read_only: true
      - type: bind
        source: ./Apache/usr/local/apache2/conf/extra/vhosts/default.conf
        target: /usr/local/apache2/conf/extra/vhosts/default.conf
        consistency: cached
        read_only: true
networks:
  internal:
volumes:
  uploads:
  solr:
  data:
