services:
  # arcadeia will be executed locally as opposed to in a container
  app: !reset null
  apache:
    extra_hosts:
        - "host.docker.internal:host-gateway"
    # apache no longer depends on arcadeia as its container is never started
    depends_on: !override
      - solr
    volumes: !override
      - type: bind
        source: ./Apache/usr/local/apache2/conf/httpd.conf
        target: /usr/local/apache2/conf/httpd.conf
        consistency: cached
        read_only: true
      - type: bind
        source: ./Apache/usr/local/apache2/conf/extra/vhosts/local.conf
        target: /usr/local/apache2/conf/extra/vhosts/default.conf
        consistency: cached
        read_only: true
  solr:
    ports:
      - "8983:8983"
