#!/bin/bash
#
# Execute a command in a container.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
pushd $SCRIPT_DIR > /dev/null 2>&1

if [ -f ".env" ]; then
  source ".env"
fi

if [ $# -eq 1 ]; then
    docker compose -f docker-compose.yml exec $@ bash
else
    docker compose -f docker-compose.yml exec $@
fi
