#!/bin/bash
#
# Start the docker compose application in production mode.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
pushd $SCRIPT_DIR > /dev/null 2>&1

if [ -f ".env" ]; then
  source ".env"
fi

docker compose logs -f $1
