#!/bin/bash
#
# Stop the docker compose application and restart it in production mode.

set -e

function show_help {
  echo "Usage: $0 [COMMAND] [SERVICE] [OPTIONS]"
  echo
  exit 0
}

if [[ "$1" == "--help" || "$1" == "-h" ]]; then
  show_help
fi

if [ -f ".env" ]; then
  source ".env"
fi

./stop $2
./start $@
