#!/bin/bash

# Get the name of the folder where the script is located
SCRIPT_DIR="$(dirname "$(realpath "$0")")"
FOLDER_NAME="$(basename "$SCRIPT_DIR")"

# Define volume names dynamically based on the folder name
VOLUMES=("${FOLDER_NAME}_data" "${FOLDER_NAME}_solr" "${FOLDER_NAME}_uploads")

# Restore each volume
echo "Restoring volumes..."
for VOLUME in "${VOLUMES[@]}"; do
    BACKUP_FILE="$SCRIPT_DIR/${VOLUME}.tar.gz"
    if [ -f "$BACKUP_FILE" ]; then
        echo "Restoring backup: $BACKUP_FILE"
        docker run --rm -v ${VOLUME}:/data -v "$SCRIPT_DIR":/backup busybox tar xzvf "/backup/${VOLUME}.tar.gz" -C /
    fi
done
