#!/bin/bash
#
# Start the docker compose application in production mode.

docker-compose -f docker-compose.yml -f docker-compose-production.yml pull
docker-compose -f docker-compose.yml -f docker-compose-production.yml up -d
