#!/bin/bash
#
# Start the docker compose application in production mode.

set -e

function show_help {
  echo "Usage: $0 [COMMAND] [SERVICE] [OPTIONS]"
  echo
  exit 0
}

if [[ "$1" == "--help" || "$1" == "-h" ]]; then
  show_help
fi

if [ -f ".env" ]; then
  source ".env"
fi

if [ ! -f "appsettings.Production.json" ]; then
  echo "{}" > "appsettings.Production.json"
fi

if [ $# -ge 1 ]; then
  export COMMAND=$1
  shift
fi

SECOND_COMPOSE_FILE="docker-compose-${COMMAND:-production}.yml"
if [ ! -f "$SECOND_COMPOSE_FILE" ]; then
  echo "Error: $SECOND_COMPOSE_FILE does not exist."
  exit 1
fi

if [ $COMMAND != "debug" ]; then
  docker compose -f docker-compose.yml -f "$SECOND_COMPOSE_FILE" pull

  if [ $# -eq 0 ]; then
    set -- -d
  fi
fi

docker compose -f docker-compose.yml -f "$SECOND_COMPOSE_FILE" up "$@"
