#!/bin/bash
#
# Start the docker compose application in production mode.

if [ -f ".env" ]; then
  source ".env"
fi

if [ ! -f "appsettings.Production.json" ]; then
  echo "{}" > "appsettings.Production.json"
fi

# Check if an argument is supplied
if [ $# -eq 1 ]; then
  export CONTAINER_TAG=$1
fi

docker compose -f docker-compose.yml -f docker-compose-production.yml pull
docker compose -f docker-compose.yml -f docker-compose-production.yml up -d
