#!/bin/bash
#
# Stop the docker compose application.

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
pushd $SCRIPT_DIR > /dev/null 2>&1

function show_help {
  echo "Usage: $0 [SERVICE] [OPTIONS]"
  echo
  exit 0
}

if [[ "$1" == "--help" || "$1" == "-h" ]]; then
  show_help
fi

if [ -f ".env" ]; then
  source ".env"
fi

docker compose down $@
