#!/bin/bash
#
# Start the docker compose application in test mode which uses the arcadeia:test image.

docker compose -f docker-compose.yml -f docker-compose-production.yml -f docker-compose-test.yml pull
docker compose -f docker-compose.yml -f docker-compose-production.yml -f docker-compose-test.yml up $1
