name: Sync to GitLab

on:
  push:
    branches:
      - master

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Sync to GitLab
        env:
          GITLAB_USERNAME: ${{ secrets.GITLAB_USERNAME }}
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
          GITLAB_REPO: ${{ secrets.GITLAB_REPO }}
          GITLAB_EMAIL: ${{ secrets.GITLAB_EMAIL }}
          GITLAB_NAME: ${{ secrets.GITLAB_NAME }}
        run: |
          git config --global user.name "$GITLAB_NAME"
          git config --global user.email "$GITLAB_EMAIL"
          git remote add gitlab https://$GITLAB_USERNAME:$GITLAB_TOKEN@$GITLAB_REPO
          git fetch gitlab master
          git merge --no-commit gitlab/master || true
          git push gitlab master
